//! Linux syscall interface — all syscall dispatch logic lives here.

use crate::errno;
use crate::task::TaskStruct;

pub fn dispatch(
    task: &mut TaskStruct,
    nr: usize,
    a0: usize, a1: usize, a2: usize,
    a3: usize, a4: usize, a5: usize,
) -> u64 {
    match nr {
        17  => crate::misc::sys_getcwd(task, a0, a1),
        23  => crate::fs::sys_dup(task, a0),
        24  => crate::fs::sys_dup3(task, a0, a1, a2),
        25  => crate::fs::sys_fcntl(task, a0, a1, a2),
        29  => crate::fs::sys_ioctl(task, a0, a1, a2),
        49  => crate::fs::sys_chdir(task, a0),
        56  => crate::fs::sys_openat(task, a0, a1, a2, a3),
        57  => crate::fs::sys_close(task, a0),
        59  => crate::fs::sys_pipe2(task, a0, a1),
        61  => crate::fs::sys_getdents64(task, a0, a1, a2),
        62  => crate::fs::sys_lseek(task, a0, a1 as isize, a2),
        63  => crate::fs::sys_read(task, a0, a1, a2),
        64  => crate::fs::sys_write(task, a0, a1, a2),
        66  => crate::fs::sys_writev(task, a0, a1, a2),
        78  => crate::fs::sys_readlinkat(task, a0, a1, a2, a3),
        79  => crate::fs::sys_newfstatat(task, a0, a1, a2, a3),
        80  => crate::fs::sys_fstat(task, a0, a1),
        93  => crate::proc::sys_exit(task, a0),
        94  => crate::proc::sys_exit_group(task, a0),
        96  => crate::proc::sys_set_tid_address(task, a0),
        98  => crate::futex::sys_futex(a0, a1, a2, a3, a4, a5),
        101 => crate::time::sys_nanosleep(a0, a1),
        113 => crate::time::sys_clock_gettime(a0, a1),
        124 => crate::proc::sys_sched_yield(),
        132 => crate::signal::sys_sigaltstack(a0, a1),
        134 => crate::signal::sys_rt_sigaction(a0, a1, a2, a3),
        135 => crate::signal::sys_rt_sigprocmask(a0, a1, a2, a3),
        153 => crate::time::sys_times(a0),
        160 => crate::misc::sys_uname(a0),
        167 => crate::proc::sys_prctl(task, a0, a1, a2, a3, a4),
        169 => crate::time::sys_gettimeofday(a0, a1),
        172 => crate::proc::sys_getpid(task),
        174 => crate::proc::sys_getuid(task),
        175 => crate::proc::sys_geteuid(task),
        176 => crate::proc::sys_getgid(task),
        177 => crate::proc::sys_getegid(task),
        178 => crate::proc::sys_gettid(task),
        214 => crate::mm::sys_brk(task, a0),
        215 => crate::mm::sys_munmap(task, a0, a1),
        220 => crate::proc::sys_clone(task, a0, a1, a2, a3, a4),
        221 => crate::proc::sys_execve(task, a0, a1, a2),
        222 => crate::mm::sys_mmap(task, a0, a1, a2, a3, a4, a5),
        226 => crate::mm::sys_mprotect(task, a0, a1, a2),
        233 => crate::mm::sys_madvise(task, a0, a1, a2),
        154 => crate::misc::sys_getpgid(a0, task.pid),
        155 => crate::misc::sys_setpgid(a0, a1),
        260 => crate::proc::sys_wait4(task, a0, a1, a2, a3),
        278 => crate::misc::sys_getrandom(a0, a1, a2),
        439 => crate::misc::sys_faccessat2(),
        _   => u64::from_le_bytes((-(errno::ENOSYS as i64)).to_le_bytes()),
    }
}
